// Bake this extension's non-code files into the bundle.
//
// A built UMD bundle cannot fetch a file next to itself - it is served from a path chosen by
// whoever installed it - so everything that is not code travels inside it:
//
//   seed/        the scripts the agent pod runs. That pod is not ours; it belongs to the agents
//                extension, so what we need in it is written there at the start of a run.
//   yaml/        the manifests a fix workspace is made of, as apps-plus App templates.
//   assets/      the sidebar icon, as a data URI (an emitted file's URL is unknowable here).
//
// Real files rather than strings built in TypeScript, so the shell is shell, the YAML is YAML,
// and both are linted and syntax-checked as themselves. `yaml/` may include a file from `seed/`
// with a line reading `@@include:<path>@@`, indented to where the content belongs - which is how
// a ConfigMap holds a script without that script having to be written as a quoted string.
//
// Run after editing any of those directories:
//   yarn gen-seed
// The output is committed, so a normal build never runs this.
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.join(here, '..', 'pkg', 'vuln-console');

function generated(body) {
  return `/* eslint-disable */\n// Generated by scripts/gen-seed.mjs. Do not edit.\n${ body }`;
}

function readDirFiles(dir, prefix = '') {
  const files = {};

  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);

    if (fs.statSync(full).isDirectory()) {
      Object.assign(files, readDirFiles(full, `${ prefix }${ name }/`));
    } else {
      files[`${ prefix }${ name }`] = fs.readFileSync(full, 'utf8');
    }
  }

  return files;
}

/**
 * Replace `@@include:<path>@@` with that file, indented to the line the marker was on.
 *
 * The indent is taken from the marker itself, so a YAML block scalar gets its content at the
 * depth the surrounding document put the marker at. A blank line is left blank rather than
 * padded, because trailing whitespace in a ConfigMap value is still whitespace.
 */
function expandIncludes(text, label) {
  return text.replace(/^([ \t]*)@@include:(.+?)@@[ \t]*$/gm, (_all, indent, target) => {
    const file = path.join(PKG, target.trim());

    if (!fs.existsSync(file)) {
      throw new Error(`${ label }: @@include:${ target }@@ names a file that does not exist`);
    }

    return fs.readFileSync(file, 'utf8')
      .replace(/\n+$/, '')
      .split('\n')
      .map((line) => (line ? indent + line : ''))
      .join('\n');
  });
}

// ── The pod's scripts ──────────────────────────────────────────────────────────────────────
const seed = readDirFiles(path.join(PKG, 'seed'));
const seedBody = Object.keys(seed)
  .map((name) => `  ${ JSON.stringify(name) }: ${ JSON.stringify(seed[name]) },`)
  .join('\n');

fs.writeFileSync(
  path.join(PKG, 'seed.generated.ts'),
  generated(`export const SEED_FILES: Record<string, string> = {\n${ seedBody }\n};\n`),
);

const seedSize = Object.values(seed).reduce((total, text) => total + Buffer.byteLength(text), 0);

console.log(`seed:  ${ Object.keys(seed).length } files, ${ (seedSize / 1024).toFixed(1) } KiB`);

// ── The workspace manifests ────────────────────────────────────────────────────────────────
const yamlDir = path.join(PKG, 'yaml');
const manifests = {};

for (const [name, text] of Object.entries(readDirFiles(yamlDir))) {
  manifests[name] = expandIncludes(text, name);
}

// `@@hash:<manifest>@@` becomes a digest of that manifest AS EXPANDED - so a Deployment can carry
// one of its ConfigMap in its pod template. A mounted ConfigMap changes under a running pod, but
// what read it at boot does not re-read it: the workspace's dev server kept a vue.config from
// before a fix for as long as the pod lived. A changed digest is a changed pod template, which
// is a rollout.
for (const [name, text] of Object.entries(manifests)) {
  manifests[name] = text.replace(/@@hash:(.+?)@@/g, (_all, target) => {
    const other = manifests[target.trim()];

    if (other === undefined) {
      throw new Error(`${ name }: @@hash:${ target }@@ names a manifest that does not exist`);
    }

    return crypto.createHash('sha256').update(other).digest('hex').slice(0, 16);
  });
}

const yamlBody = Object.keys(manifests)
  .map((name) => `  ${ JSON.stringify(name) }: ${ JSON.stringify(manifests[name]) },`)
  .join('\n');

fs.writeFileSync(
  path.join(PKG, 'yaml.generated.ts'),
  generated(`export const MANIFESTS: Record<string, string> = {\n${ yamlBody }\n};\n`),
);

const yamlSize = Object.values(manifests).reduce((total, text) => total + Buffer.byteLength(text), 0);

console.log(`yaml:  ${ Object.keys(manifests).length } files, ${ (yamlSize / 1024).toFixed(1) } KiB`);

// ── The sidebar icon ───────────────────────────────────────────────────────────────────────
// base64 rather than percent-encoded utf8: it survives every place a data URI gets copied
// through, and the icon is small enough that the extra third is nothing.
const navIcon = fs.readFileSync(path.join(PKG, 'assets', 'nav-icon.svg'));
const dataUri = `data:image/svg+xml;base64,${ navIcon.toString('base64') }`;

fs.writeFileSync(
  path.join(PKG, 'icon.generated.ts'),
  generated(`export const NAV_ICON: string = ${ JSON.stringify(dataUri) };\n`),
);

console.log(`icon:  nav-icon.svg, ${ navIcon.length } bytes -> ${ dataUri.length } char data URI`);
