// The scheduled gather, as objects this extension keeps in the cluster.
//
// WHY NOT IN THE HELM CHART. The chart is generated by rancher/dashboard's own publish script,
// which copies its `ui-plugin-server` template - Chart.yaml, values.yaml, a UIPlugin CR - and
// offers no hook for an extra template. It is a third party's workflow with write access to
// this repository; forking it to smuggle a CronJob in would be a maintenance burden with a
// sharp edge. So the extension creates these the way it already creates its namespace, its
// Secret and its apps-plus Apps: on the page, reconciled every time a board mounts, which also
// means deleting one by hand is repaired rather than permanent.
//
// WHAT IT RUNS. `cron-gather.mjs`, which shells out to the very same `gather.mjs` a person's
// Refresh runs. The gather is the part that must not drift between the scheduled path and the
// manual one, so there is one of it.
import { NAMESPACE, SECRET_NAME, SETTINGS_NAMESPACE } from '../config/constants';
import type { Board } from '../config/constants';
import { STEVE_BASE, rancherFetch } from './rancher';
import { SEED_FILES } from '../seed.generated';
import { TRACKED_REPOS } from '../config/repos';

const NAME = 'vuln-gather';
/** The history rebuild is its own job on its own clock - see HISTORY_SCHEDULE. */
const HISTORY_NAME = 'vuln-history';

/**
 * Every half hour.
 *
 * The console this replaces re-gathered hourly and called the calls cheap, which they are:
 * Dependabot alerts and two files per board. Half an hour was asked for and costs nothing
 * more that matters - the work is the same handful of API calls either way.
 */
const SCHEDULE = '*/30 * * * *';

/**
 * Daily, at a quiet hour.
 *
 * The series is bucketed by WEEK, so running it more often redraws the same picture while
 * spending a full alert pull on every repository - about forty API calls - on a number that
 * cannot have moved. Half past three because nothing else here runs then.
 */
const HISTORY_SCHEDULE = '30 3 * * *';

/** A stock node image. The job needs no kubectl: it talks to the apiserver itself. */
const IMAGE = 'node:24-alpine';

function steve(path: string, init?: RequestInit): Promise<any> {
  return rancherFetch(`${ STEVE_BASE }${ path }`, init);
}

/** Create it if it is not there, leave it alone if it is - except the parts that change. */
async function apply(type: string, name: string, body: Record<string, unknown>, namespace = NAMESPACE): Promise<void> {
  const existing = await steve(`/${ type }/${ namespace }/${ name }`).catch(() => null);

  if (existing) {
    await steve(`/${ type }/${ namespace }/${ name }`, {
      method: 'PUT',
      body:   JSON.stringify({ ...body, metadata: { ...(body.metadata as object), resourceVersion: existing.metadata?.resourceVersion } }),
    }).catch(() => undefined);

    return;
  }

  await steve(`/${ type }`, { method: 'POST', body: JSON.stringify(body) }).catch((e: any) => {
    if (!/409|already exists|alreadyexists/i.test(e?.message || '')) {
      throw e;
    }
  });
}

/**
 * What the job may do, and nothing else.
 *
 * Read one Secret in the settings namespace, write the snapshot ConfigMaps in its own. Not
 * cluster-admin, and not the agents pod's ServiceAccount, which is - a scheduled job that only
 * needs two verbs should hold two verbs.
 */
function rbac(): { type: string; name: string; namespace: string; body: Record<string, unknown> }[] {
  const subject = { kind: 'ServiceAccount', name: NAME, namespace: NAMESPACE };

  return [
    {
      type:      'serviceaccount',
      name:      NAME,
      namespace: NAMESPACE,
      body:      { apiVersion: 'v1', kind: 'ServiceAccount', metadata: { name: NAME, namespace: NAMESPACE } },
    },
    {
      type:      'rbac.authorization.k8s.io.role',
      name:      NAME,
      namespace: NAMESPACE,
      body:      {
        apiVersion: 'rbac.authorization.k8s.io/v1',
        kind:       'Role',
        metadata:   { name: NAME, namespace: NAMESPACE },
        rules:      [{ apiGroups: [''], resources: ['configmaps'], verbs: ['get', 'list', 'create', 'update', 'patch'] }],
      },
    },
    {
      type:      'rbac.authorization.k8s.io.rolebinding',
      name:      NAME,
      namespace: NAMESPACE,
      body:      {
        apiVersion: 'rbac.authorization.k8s.io/v1',
        kind:       'RoleBinding',
        metadata:   { name: NAME, namespace: NAMESPACE },
        roleRef:    { apiGroup: 'rbac.authorization.k8s.io', kind: 'Role', name: NAME },
        subjects:   [subject],
      },
    },
    {
      type:      'rbac.authorization.k8s.io.role',
      name:      `${ NAME }-settings`,
      namespace: SETTINGS_NAMESPACE,
      body:      {
        apiVersion: 'rbac.authorization.k8s.io/v1',
        kind:       'Role',
        metadata:   { name: `${ NAME }-settings`, namespace: SETTINGS_NAMESPACE },
        // By name. A job that can read every Secret in the namespace is a job that can read
        // the next one somebody puts there.
        rules: [{
          apiGroups: [''], resources: ['secrets'], resourceNames: [SECRET_NAME], verbs: ['get'],
        }],
      },
    },
    {
      type:      'rbac.authorization.k8s.io.rolebinding',
      name:      `${ NAME }-settings`,
      namespace: SETTINGS_NAMESPACE,
      body:      {
        apiVersion: 'rbac.authorization.k8s.io/v1',
        kind:       'RoleBinding',
        metadata:   { name: `${ NAME }-settings`, namespace: SETTINGS_NAMESPACE },
        roleRef:    { apiGroup: 'rbac.authorization.k8s.io', kind: 'Role', name: `${ NAME }-settings` },
        subjects:   [subject],
      },
    },
  ];
}

function scriptsBody(): Record<string, unknown> {
  const data: Record<string, string> = {};

  for (const name of ['gather.mjs', 'cron-gather.mjs', 'history.mjs', 'cron-history.mjs']) {
    const content = SEED_FILES[name];

    if (!content) {
      throw new Error(`This build is missing its ${ name } - run "yarn gen-seed" and rebuild.`);
    }

    data[name] = content;
  }

  return {
    apiVersion: 'v1',
    kind:       'ConfigMap',
    metadata:   { name: `${ NAME }-scripts`, namespace: NAMESPACE },
    data,
  };
}

function cronBody(boards: Board[]): Record<string, unknown> {
  return {
    apiVersion: 'batch/v1',
    kind:       'CronJob',
    metadata:   { name: NAME, namespace: NAMESPACE },
    spec:       {
      schedule:                   SCHEDULE,
      // A gather that overran must not have a second one started on top of it, and a cluster
      // asleep for a day should wake to one run rather than forty-eight.
      concurrencyPolicy:          'Forbid',
      startingDeadlineSeconds:    300,
      successfulJobsHistoryLimit: 1,
      failedJobsHistoryLimit:     3,
      jobTemplate:                {
        spec: {
          backoffLimit: 1,
          template:     {
            spec: {
              serviceAccountName: NAME,
              restartPolicy:      'Never',
              // Nothing here needs root, a filesystem or a capability: it reads two files from
              // a projected volume, makes HTTPS calls and writes to /tmp. Say so, so a cluster
              // with a restricted PodSecurity level admits it rather than rejecting the only
              // thing keeping the board current.
              securityContext: {
                runAsNonRoot: true, runAsUser: 1000, runAsGroup: 1000, fsGroup: 1000, seccompProfile: { type: 'RuntimeDefault' },
              },
              containers:         [{
                name:    'gather',
                image:   IMAGE,
                command: ['node', '/seed/cron-gather.mjs'],
                env:     [
                  { name: 'VULN_NAMESPACE', value: NAMESPACE },
                  { name: 'SETTINGS_NAMESPACE', value: SETTINGS_NAMESPACE },
                  { name: 'SETTINGS_SECRET', value: SECRET_NAME },
                  // The apiserver's own CA, so node trusts it without --insecure.
                  { name: 'NODE_EXTRA_CA_CERTS', value: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt' },
                  {
                    name:  'BOARDS',
                    value: JSON.stringify(boards.map((b) => ({
                      id: b.id, repo: b.repo, rancherPackages: b.rancherPackages || [],
                    }))),
                  },
                ],
                securityContext: { allowPrivilegeEscalation: false, capabilities: { drop: ['ALL'] } },
                volumeMounts:    [{ name: 'seed', mountPath: '/seed' }],
                resources:    { requests: { cpu: '50m', memory: '128Mi' }, limits: { memory: '512Mi' } },
              }],
              volumes: [{ name: 'seed', configMap: { name: `${ NAME }-scripts` } }],
            },
          },
        },
      },
    },
  };
}

/**
 * The history rebuild: same pod shape, same ServiceAccount, its own clock.
 *
 * It needs exactly what the gather needs - read one Secret, write one ConfigMap - so it borrows
 * the RBAC rather than growing a second copy of it.
 */
function historyCronBody(): Record<string, unknown> {
  return {
    apiVersion: 'batch/v1',
    kind:       'CronJob',
    metadata:   { name: HISTORY_NAME, namespace: NAMESPACE },
    spec:       {
      schedule:                   HISTORY_SCHEDULE,
      concurrencyPolicy:          'Forbid',
      startingDeadlineSeconds:    3600,
      successfulJobsHistoryLimit: 1,
      failedJobsHistoryLimit:     3,
      jobTemplate:                {
        spec: {
          backoffLimit: 1,
          template:     {
            spec: {
              serviceAccountName: NAME,
              restartPolicy:      'Never',
              securityContext:    {
                runAsNonRoot: true, runAsUser: 1000, runAsGroup: 1000, fsGroup: 1000, seccompProfile: { type: 'RuntimeDefault' },
              },
              containers: [{
                name:    'history',
                image:   IMAGE,
                command: ['node', '/seed/cron-history.mjs'],
                env:     [
                  { name: 'VULN_NAMESPACE', value: NAMESPACE },
                  { name: 'SETTINGS_NAMESPACE', value: SETTINGS_NAMESPACE },
                  { name: 'SETTINGS_SECRET', value: SECRET_NAME },
                  { name: 'NODE_EXTRA_CA_CERTS', value: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt' },
                  { name: 'REPOS', value: JSON.stringify(TRACKED_REPOS) },
                ],
                securityContext: { allowPrivilegeEscalation: false, capabilities: { drop: ['ALL'] } },
                volumeMounts:    [{ name: 'seed', mountPath: '/seed' }],
                resources:       { requests: { cpu: '50m', memory: '128Mi' }, limits: { memory: '512Mi' } },
              }],
              volumes: [{ name: 'seed', configMap: { name: `${ NAME }-scripts` } }],
            },
          },
        },
      },
    },
  };
}

/**
 * Put the schedule in place, and keep it matching this build.
 *
 * Called on board mount. The CronJob carries the board list and the scripts, so an extension
 * upgrade that adds a board or changes the gather is picked up the first time somebody opens
 * the console rather than needing anybody to remember.
 */
export async function ensureGatherCron(boards: Board[]): Promise<void> {
  for (const item of rbac()) {
    await apply(item.type, item.name, item.body, item.namespace);
  }

  await apply('configmap', `${ NAME }-scripts`, scriptsBody());
  await apply('batch.cronjob', NAME, cronBody(boards));
  await apply('batch.cronjob', HISTORY_NAME, historyCronBody());
}
